# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app_llamaparse

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application's code into the container at /app
COPY app_llamaparse.py .

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Define the command to run your app
# Variant II - LlamaParseReader
CMD ["streamlit", "run", "app_llamaparse.py", "--server.port=8501", "--server.address=0.0.0.0"]

# Variant I - pdfplumber
# CMD ["streamlit", "run", "app_llamaparse.py", "--server.port=8501", "--server.address=0.0.0.0"]

#Bash

#docker run -p 8501:8501 -it doc-chat-app
#Open your browser and go to http://localhost:8501.





